language: go

go:
  - 1.8
  - 1.9

env:
  - DEP_VERSION="0.3.2" PROJECT=$GOPATH/src/continuul.io

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

script:
  - git clone --depth=50 --branch=master https://github.com/continuul/adm.git $GOPATH/src/continuul.io/adm
  - cd $GOPATH/src/continuul.io/adm
  - dep ensure
  - make all
